version: '3.8'
services:
  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - .env
  database:
    image: postgres:latest
    user: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 2s
      timeout: 60s
    volumes:
      - zumm_postgres:/var/lib/postgresql/data

volumes:
  zumm_postgres: